CREATE TABLE tools (
  id VARCHAR PRIMARY KEY,
  name VARCHAR NOT NULL,
  title VARCHAR NOT NULL,
  short_description TEXT NOT NULL,
  long_description TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add trigger to automatically update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_tools_updated_at
    BEFORE UPDATE ON tools
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insert initial data
INSERT INTO tools (id, name, title, short_description, long_description) VALUES
  ('title-case', 'Title Case', 'Title Case Converter - Free Online Text Case Converter', 'Convert your text to title case online. This free tool automatically capitalizes the first letter of each word. Perfect for formatting headlines, titles, and headings.', '<h2>How Does the Title Case Generator Work?</h2><p>Type out or copy and paste your content into the left panel. As you do this, you should see that the right panel automatically converts your text into title case format. You can then copy and paste that title case content wherever you need to.</p><p>In Title Case, The First Letter Of Each Word Is Capitalized. This Format Is Commonly Used For Headlines, Book Titles, Article Titles, And Other Headings.</p><h2>Features of Our Title Case Converter</h2><ul><li>Automatically capitalizes the first letter of each word</li><li>Maintains proper spacing and punctuation</li><li>Real-time conversion as you type</li><li>Preserves original formatting and line breaks</li><li>Includes character, word, sentence, and line counting</li><li>Easy copy-to-clipboard and download options</li></ul>'),
  ('uppercase', 'UPPERCASE', 'UPPERCASE Converter - Free Online Text Case Converter', 'Convert your text to UPPERCASE online. This free tool transforms all letters to capital letters. Perfect for creating emphasis, headers, or when uppercase text is required.', '<h2>How Does the UPPERCASE Generator Work?</h2><p>Type out or copy and paste your content into the left panel. As you do this, you should see that the right panel automatically converts your text into uppercase format. You can then copy and paste that uppercase content wherever you need to.</p><p>UPPERCASE TEXT IS COMMONLY USED FOR EMPHASIS, HEADERS, OR WHEN REQUIRED BY SPECIFIC STYLE GUIDES. IT CAN ALSO BE USEFUL FOR CREATING ATTENTION-GRABBING HEADLINES OR IMPORTANT NOTICES.</p><h2>Features of Our UPPERCASE Converter</h2><ul><li>Converts all letters to uppercase instantly</li><li>Maintains spacing and punctuation</li><li>Real-time conversion as you type</li><li>Preserves original formatting and line breaks</li><li>Includes character, word, sentence, and line counting</li><li>Easy copy-to-clipboard and download options</li></ul>'),
  ('lowercase', 'lowercase', 'lowercase Converter - Free Online Text Case Converter', 'Convert your text to lowercase online. This free tool transforms all letters to small letters. Perfect for coding, formatting, or when lowercase text is required.', '<h2>How Does the lowercase Generator Work?</h2><p>type out or copy and paste your content into the left panel. as you do this, you should see that the right panel automatically converts your text into lowercase format. you can then copy and paste that lowercase content wherever you need to.</p><p>lowercase text is commonly used in coding (for variables and functions), in certain design styles, or when a more casual or modern look is desired. it can also be useful for maintaining consistency in technical documentation.</p><h2>Features of Our lowercase Converter</h2><ul><li>converts all letters to lowercase instantly</li><li>maintains spacing and punctuation</li><li>real-time conversion as you type</li><li>preserves original formatting and line breaks</li><li>includes character, word, sentence, and line counting</li><li>easy copy-to-clipboard and download options</li></ul>'),
  ('alternating-case', 'aLtErNaTiNg cAsE', 'aLtErNaTiNg cAsE Converter - Free Online Text Case Converter', 'Convert your text to alternating case online. This free tool alternates between uppercase and lowercase letters. Perfect for creating fun, stylized text.', '<h2>How Does the aLtErNaTiNg cAsE Generator Work?</h2><p>Type out or copy and paste your content into the left panel. As you do this, you should see that the right panel automatically converts your text into alternating case format. You can then copy and paste that alternating case content wherever you need to.</p><p>AlTeRnAtInG cAsE iS oFtEn UsEd FoR cReAtInG a PlAyFuL oR sTyLiZeD lOoK. iT''s PoPuLaR iN sOcIaL mEdIa AnD iNfOrMaL cOmMuNiCaTiOn.</p><h2>Features of Our aLtErNaTiNg cAsE Converter</h2><ul><li>Alternates between uppercase and lowercase letters</li><li>Maintains spacing and punctuation</li><li>Real-time conversion as you type</li><li>Preserves original formatting and line breaks</li><li>Includes character, word, sentence, and line counting</li><li>Easy copy-to-clipboard and download options</li></ul>'),
  ('text-counter', 'Text Counter', 'Text Counter - Free Online Text Statistics Tool', 'Count characters, words, sentences, and paragraphs in your text online. This free tool provides detailed statistics about your text content.', '<h2>About Our Text Counter Tool</h2><p>Our text counter tool provides comprehensive statistics about your text content. Whether you''re writing an essay, article, or social media post, this tool helps you understand the length and complexity of your content.</p><h2>Features of Our Text Counter</h2><ul><li>Character count (with and without spaces)</li><li>Word count and unique word count</li><li>Sentence and paragraph count</li><li>Line count</li><li>Estimated reading time</li><li>Real-time statistics as you type</li><li>Easy copy-to-clipboard functionality</li></ul><h2>How to Use</h2><ol><li>Type or paste your text into the input area</li><li>View the statistics update in real-time</li><li>Use the copy button to save the statistics</li><li>Clear the input to start over</li></ol>');